on:
  #push:
  #  # Sequence of patterns matched against refs/tags
  #  tags:
  #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Tar and Zip File
        run: |
          tar -czvf JuliaMono.tar.gz JuliaMono-*.ttf LICENSE
          zip JuliaMono.zip JuliaMono-*.ttf LICENSE
          #- name: Create Release
          #  id: create_release
          #  uses: actions/create-release@v1
          #  env:
          #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #  with:
          #    tag_name: ${{ github.ref }}
          #    release_name: Release ${{ github.ref }}
          #    draft: false
          #    prerelease: false
          #  if: 
      - name: Upload Tar File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JuliaMono.tar.gz
          asset_name: JuliaMono.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload Zip File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JuliaMono.zip
          asset_name: JuliaMono.zip
          asset_content_type: application/zip
